---
- name: Ubuntu Workstation Provisioning
  hosts: localhost
  connection: local
  become: yes

  vars:
    real_user: "{{ lookup('env', 'USER') | default(lookup('env', 'LOGNAME'), true) | default(lookup('pipe', 'whoami'), true) }}"
    real_home: "{{ lookup('env', 'HOME') | default('/home/' + real_user, true) }}"

  roles:
    - common
    - docker
    - asdf
    - brave
    - 1password
    - alacritty
    - oh-my-zsh
    - cli_tools
    - dbeaver
    - ides
    - omakub_tools
    - dotfiles
