---
- name: Download DBeaver GPG key
  ansible.builtin.get_url:
    url: https://dbeaver.io/debs/dbeaver.gpg.key
    dest: /usr/share/keyrings/dbeaver.gpg.key
    mode: '0644'

- name: Add DBeaver repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/dbeaver.gpg.key] https://dbeaver.io/debs/dbeaver-ce /"
    state: present
    update_cache: yes
    filename: dbeaver

- name: Install DBeaver CE
  ansible.builtin.apt:
    name: dbeaver-ce
    state: present
