---
- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'
  become: no

- name: Ensure .config/starship exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/starship"
    state: directory
    mode: '0755'
  become: no

- name: Copy .zshrc
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: '0644'
    backup: yes
  become: no

- name: Copy starship.toml
  ansible.builtin.copy:
    src: starship.toml
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    mode: '0644'
  become: no
