---
- name: Create directory for GitHub CLI keyring
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download GitHub CLI GPG key
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'

- name: Add GitHub CLI repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    state: present
    update_cache: yes
    filename: github-cli

- name: Install CLI Tools (lazygo, gh, jq, fzf, ripgrep, bat)
  ansible.builtin.apt:
    name:
      - gh
      - jq
      - fzf
      - ripgrep
      - bat
    state: present
- name: Create local bin directory
  ansible.builtin.file:
    path: "{{ real_home }}/.local/bin"
    state: directory
    mode: '0755'
  become: no

- name: Install lazygit via script
  ansible.builtin.shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | jq -r .tag_name)
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION//v/}_Linux_x86_64.tar.gz"
    tar xf lazygit.tar.gz lazygit
    install lazygit {{ real_home }}/.local/bin
    rm lazygit.tar.gz lazygit
  args:
    executable: /bin/bash
    creates: "{{ real_home }}/.local/bin/lazygit"
  become: no



- name: Download lazydocker install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
    dest: /tmp/install_lazydocker.sh
    mode: '0755'
  become: no

- name: Install lazydocker
  ansible.builtin.command: /tmp/install_lazydocker.sh
  args:
    creates: "{{ real_home }}/.local/bin/lazydocker"
  become: no
